In [1]:
import pandas as pd
import requests

In [60]:
url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiMTA1ODJhYWNhNTZlZGVkMThhNDBjYjkyNDQyZDIzZiIsIm5iZiI6MTc1ODU4MDQ2Mi42LCJzdWIiOiI2OGQxY2VlZTc3NWMyNjZlYTNjYzNjYjAiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.2YJeC_Y1lSOilh3V2JWu3jL2uxSHO2GdlRlxjN-3poI"
}

response = requests.get(url, headers=headers)

In [43]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [44]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,28.5814,8.712,28901
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,30.7040,8.685,21846
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,15.6700,8.570,13194
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,15.4034,8.566,16716
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,13.7100,8.500,9407

In [19]:
dfs = []

In [45]:
for i in range(1,501):
  url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}"
  response = requests.get(url, headers=headers)
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  dfs.append(temp_df)
df = pd.concat(dfs,ignore_index=True)

In [58]:
df = df.drop_duplicates()

In [63]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,28.5814,8.712,28901
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,30.7040,8.685,21846
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,15.6700,8.570,13194
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,15.4034,8.566,16716
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,13.7100,8.500,9407
...,...,...,...,...,...,...,...
9998,9405,Double Team,A CIA agent is interned for failing to kill an...,1997-04-04,2.6655,5.200,788
9999,13788,The Unborn,A young woman fights the spirit that is slowly...,2009-01-09,3.7555,5.181,1385
16788,8839,Casper,Casper is a kind young ghost who peacefully ha...,1995-05-26,6.3722,6.330,4724
29444,7233,Rebound,An acclaimed college hoops coach is demoted to...,2005-07-01,1.0731,5.590,338
29447,10802,Showgirls,"Fresh to Las Vegas with no connections, Nomi M...",1995-09-22,8.3686,5.600,1305

In [64]:
df.to_csv('movies.csv',index=False)