### Pandas Export

- to csv
- to excel
- to html
- to json
- to sql

## to_csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('deliveries.csv')
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [6]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4       A Dananjaya             4
..              ...           ...
511     YV Takawale           192
512   Yashpal Singh            47
513     Younis Khan             3
514    Yuvraj Singh          2765
515          Z Khan           117

[516 rows x 2 columns]

In [8]:
temp_df.to_csv('batsman_runs.csv',index=False)

In [10]:
df.pivot_table(index='batsman',columns='bowling_team',values='batsman_runs',aggfunc='sum').to_csv('batsman_vs_team.csv')

## to_excel

In [11]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [12]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()

In [13]:
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4       A Dananjaya             4
..              ...           ...
511     YV Takawale           192
512   Yashpal Singh            47
513     Younis Khan             3
514    Yuvraj Singh          2765
515          Z Khan           117

[516 rows x 2 columns]

In [15]:
temp_df.to_excel("batsman_runs.xlsx",index=False)

In [17]:
temp_df.to_excel("output.xlsx",sheet_name='batsman_runs',index=False)

In [18]:
temp_df2 = df.pivot_table(index='batsman',columns='bowling_team',values='batsman_runs',aggfunc='sum')

In [32]:
temp_df2

bowling_team,Chennai Super Kings,Deccan Chargers,Delhi Capitals,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
batsman,,,,,,,,,,,,,,,
A Ashish Reddy,45.0,NaN,NaN,36.0,NaN,37.0,NaN,17.0,27.0,26.0,37.0,NaN,NaN,55.0,NaN
A Chandila,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
A Chopra,NaN,35.0,NaN,13.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN
A Choudhary,NaN,NaN,NaN,NaN,15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
A Dananjaya,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YV Takawale,19.0,5.0,NaN,14.0,NaN,0.0,NaN,85.0,NaN,NaN,69.0,NaN,NaN,NaN,NaN
Yashpal Singh,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,8.0,NaN,26.0,NaN,NaN,NaN,NaN
Younis Khan,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yuvraj Singh,345.0,118.0,59.0,459.0,13.0,260.0,8.0,386.0,275.0,NaN,384.0,47.0,23.0,340.0,48.0
Z Khan,39.0,4.0,NaN,4.0,NaN,1.0,NaN,20.0,5.0,NaN,18.0,NaN,NaN,25.0,1.0

In [19]:
with pd.ExcelWriter('output.xlsx') as writer:
  temp_df.to_excel(writer,sheet_name ='sheet_name_1')
  temp_df2.to_excel(writer,sheet_name= ' sheet_name_2')

## to_html

In [ ]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [20]:
df.query('batsman_runs == 6').pivot_table(index='over',columns='ball',values='batsman_runs',aggfunc='count').to_html('sixes_heatmap.html')

## to_json

In [21]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [31]:
df.groupby(['batting_team','batsman'])['batsman_runs'].sum().unstack()

batsman,A Ashish Reddy,A Chandila,A Chopra,A Choudhary,A Dananjaya,A Flintoff,A Hales,A Joseph,A Kumble,A Mishra,...,Y Nagar,Y Venugopal Rao,YA Abdulla,YK Pathan,YS Chahal,YV Takawale,Yashpal Singh,Younis Khan,Yuvraj Singh,Z Khan
batting_team,,,,,,,,,,,,,,,,,,,,,
Chennai Super Kings,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Deccan Chargers,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,...,NaN,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Daredevils,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.0,...,285.0,468.0,NaN,NaN,NaN,NaN,NaN,NaN,248.0,10.0
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kings XI Punjab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,964.0,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1893.0,NaN,NaN,47.0,NaN,NaN,NaN
Mumbai Indians,NaN,NaN,NaN,NaN,4.0,NaN,NaN,15.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,88.0,NaN,NaN,108.0,40.0
Pune Warriors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.0,NaN
Rajasthan Royals,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1029.0,NaN,NaN,NaN,3.0,NaN,NaN
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,35.0,NaN,...,NaN,NaN,NaN,NaN,22.0,104.0,NaN,NaN,376.0,67.0
Sunrisers Hyderabad,245.0,NaN,NaN,NaN,NaN,NaN,152.0,NaN,NaN,93.0,...,NaN,71.0,NaN,319.0,NaN,NaN,NaN,NaN,488.0,NaN

In [22]:
df.groupby(['batting_team','batsman'])['batsman_runs'].sum().unstack().to_json('ipl.json')

## to_sql

In [ ]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [ ]:
import pymysql
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("mysql+pymysql://root:@localhost/ipl")
# {root}:{password}@{url}/{database}
df.to_sql('ipl_delivery', con = engine, if_exists = 'append')

In [ ]:
temp_df.to_sql('batsman_runs', con = engine, if_exists = 'append')

In [ ]:
temp_df2

bowling_team,Chennai Super Kings,Deccan Chargers,Delhi Capitals,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
batsman,,,,,,,,,,,,,,,
A Ashish Reddy,45.0,NaN,NaN,36.0,NaN,37.0,NaN,17.0,27.0,26.0,37.0,NaN,NaN,55.0,NaN
A Chandila,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
A Chopra,NaN,35.0,NaN,13.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN
A Choudhary,NaN,NaN,NaN,NaN,15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
A Dananjaya,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YV Takawale,19.0,5.0,NaN,14.0,NaN,0.0,NaN,85.0,NaN,NaN,69.0,NaN,NaN,NaN,NaN
Yashpal Singh,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,8.0,NaN,26.0,NaN,NaN,NaN,NaN
Younis Khan,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yuvraj Singh,345.0,118.0,59.0,459.0,13.0,260.0,8.0,386.0,275.0,NaN,384.0,47.0,23.0,340.0,48.0
Z Khan,39.0,4.0,NaN,4.0,NaN,1.0,NaN,20.0,5.0,NaN,18.0,NaN,NaN,25.0,1.0

In [ ]:
six_df = df.query('batsman_runs == 6').pivot_table(index='over',columns='ball',values='batsman_runs',aggfunc='count')

In [ ]:
six_df.to_sql('six_heatmap', con = engine, if_exists = 'append')